/** EPIC-8 M1/M2 — report_type UI 映射 (FR-701/702/703/704) */

export type ReportType = 'DIAGNOSTIC' | 'WEEKLY' | 'MONTHLY' | 'CUSTOM';

export type ReportSectionKey =
  | 'geo'
  | 'keywords'
  | 'content'
  | 'landing'
  | 'leads'
  | 'recommendations';

export const REPORT_TYPE_META: Record<
  ReportType,
  { label: string; type: 'primary' | 'success' | 'warning' | 'info' }
> = {
  DIAGNOSTIC: { label: '诊断报告', type: 'primary' },
  WEEKLY: { label: '增长周报', type: 'success' },
  MONTHLY: { label: '增长月报', type: 'warning' },
  CUSTOM: { label: '自定义', type: 'info' }
};

export const REPORT_SECTION_OPTIONS: { value: ReportSectionKey; label: string }[] = [
  { value: 'geo', label: 'GEO 可见率与变化' },
  { value: 'keywords', label: '关键词机会' },
  { value: 'content', label: '内容产出' },
  { value: 'landing', label: '落地页' },
  { value: 'leads', label: '询盘与 CRM' },
  { value: 'recommendations', label: '优化建议' }
];

export const DEFAULT_REPORT_SECTIONS: ReportSectionKey[] = REPORT_SECTION_OPTIONS.map((o) => o.value);

export const DEFAULT_REPORT_TEMPLATE = {
  coverTitle: 'Inbound Growth Report',
  companyName: 'TourGEO Agent',
  primaryColor: '#1677a0',
  footerText: 'Generated by TourGEO Agent',
  logoUrl: '',
  sections: [...DEFAULT_REPORT_SECTIONS] as ReportSectionKey[]
};

export const REPORT_TYPE_OPTIONS = Object.entries(REPORT_TYPE_META).map(([value, meta]) => ({
  value,
  label: meta.label
}));

export const WEEKLY_REPORT_DISCLAIMER =
  '免责声明：数据来自系统统计区间，不构成 AI 推荐排名承诺。';

export function reportTypeMeta(type: string) {
  return (
    REPORT_TYPE_META[type as ReportType] ?? {
      label: type,
      type: 'info' as const
    }
  );
}

/** ISO week label YYYY-Www from a Date (UTC-based, Monday week). */
export function isoWeekLabel(date: Date): string {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const day = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - day);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const week = Math.ceil(((d.getTime() - yearStart.getTime()) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${String(week).padStart(2, '0')}`;
}

export function formatYmd(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, '0');
  const d = String(date.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

export function defaultWeeklyRange(): [string, string] {
  const end = new Date();
  const start = new Date();
  start.setDate(end.getDate() - 6);
  return [formatYmd(start), formatYmd(end)];
}

/** 默认上一完整自然月，格式 YYYY-MM */
export function defaultPreviousMonthStr(): string {
  const now = new Date();
  let year = now.getFullYear();
  let month = now.getMonth();
  month -= 1;
  if (month < 0) {
    month = 11;
    year -= 1;
  }
  return `${year}-${String(month + 1).padStart(2, '0')}`;
}

export function parseMonthStr(monthStr: string): { year: number; month: number } | null {
  const m = /^(\d{4})-(\d{2})$/.exec(monthStr);
  if (!m) return null;
  const year = Number(m[1]);
  const month = Number(m[2]);
  if (month < 1 || month > 12) return null;
  return { year, month };
}

/** 自然月展示：2026-06 → 2026年6月 */
export function formatMonthLabel(period?: string): string {
  if (!period) return '—';
  const parsed = parseMonthStr(period);
  if (!parsed) return period;
  return `${parsed.year}年${parsed.month}月`;
}

/** 自然月首尾日期 */
export function monthRangeFromPeriod(period: string): { start: string; end: string } | null {
  const parsed = parseMonthStr(period);
  if (!parsed) return null;
  const lastDay = new Date(parsed.year, parsed.month, 0).getDate();
  const mm = String(parsed.month).padStart(2, '0');
  return {
    start: `${parsed.year}-${mm}-01`,
    end: `${parsed.year}-${mm}-${String(lastDay).padStart(2, '0')}`
  };
}

export function disableFutureMonth(date: Date): boolean {
  const now = new Date();
  const y = date.getFullYear();
  const m = date.getMonth();
  if (y > now.getFullYear()) return true;
  if (y === now.getFullYear() && m > now.getMonth()) return true;
  return false;
}
