package org.dromara.project.report;

import lombok.Builder;
import lombok.Data;
import org.dromara.common.core.utils.StringUtils;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * Tenant report white-label config — EPIC-8 FR-704.
 */
@Data
@Builder
public class ReportBranding {

    private static final String DEFAULT_COVER = "Inbound Growth Report";
    private static final String DEFAULT_COMPANY = "TourGEO Agent";
    private static final String DEFAULT_COLOR = "#1677a0";
    private static final String DEFAULT_FOOTER = "Generated by TourGEO Agent";

    private String logoUrl;
    private String coverTitle;
    private String companyName;
    private String primaryColor;
    private String footerText;
    @Builder.Default
    private List<String> sections = defaultSections();

    public static List<String> defaultSections() {
        return List.of("geo", "keywords", "content", "landing", "leads", "recommendations");
    }

    public static ReportBranding defaults() {
        return ReportBranding.builder()
            .coverTitle(DEFAULT_COVER)
            .companyName(DEFAULT_COMPANY)
            .primaryColor(DEFAULT_COLOR)
            .footerText(DEFAULT_FOOTER)
            .sections(defaultSections())
            .build();
    }

    @SuppressWarnings("unchecked")
    public static ReportBranding fromConfig(Map<String, Object> config) {
        if (config == null || config.isEmpty()) {
            return defaults();
        }
        List<String> sections = new ArrayList<>();
        Object rawSections = config.get("sections");
        if (rawSections instanceof List<?> list) {
            for (Object item : list) {
                if (item != null && StringUtils.isNotBlank(String.valueOf(item))) {
                    sections.add(String.valueOf(item).trim());
                }
            }
        }
        if (sections.isEmpty()) {
            sections = defaultSections();
        }
        return ReportBranding.builder()
            .logoUrl(stringVal(config.get("logoUrl")))
            .coverTitle(StringUtils.blankToDefault(stringVal(config.get("coverTitle")), DEFAULT_COVER))
            .companyName(StringUtils.blankToDefault(stringVal(config.get("companyName")), DEFAULT_COMPANY))
            .primaryColor(StringUtils.blankToDefault(stringVal(config.get("primaryColor")), DEFAULT_COLOR))
            .footerText(StringUtils.blankToDefault(stringVal(config.get("footerText")), DEFAULT_FOOTER))
            .sections(sections)
            .build();
    }

    public Map<String, Object> toConfigMap() {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("logoUrl", StringUtils.blankToDefault(logoUrl, ""));
        map.put("coverTitle", StringUtils.blankToDefault(coverTitle, DEFAULT_COVER));
        map.put("companyName", StringUtils.blankToDefault(companyName, DEFAULT_COMPANY));
        map.put("primaryColor", StringUtils.blankToDefault(primaryColor, DEFAULT_COLOR));
        map.put("footerText", StringUtils.blankToDefault(footerText, DEFAULT_FOOTER));
        map.put("sections", sections != null ? sections : defaultSections());
        return map;
    }

    public Map<String, Object> toSnapshot() {
        Map<String, Object> snap = new LinkedHashMap<>();
        snap.put("companyName", StringUtils.blankToDefault(companyName, DEFAULT_COMPANY));
        snap.put("primaryColor", StringUtils.blankToDefault(primaryColor, DEFAULT_COLOR));
        if (StringUtils.isNotBlank(coverTitle)) {
            snap.put("coverTitle", coverTitle);
        }
        return snap;
    }

    public String safePrimaryColor() {
        String color = StringUtils.blankToDefault(primaryColor, DEFAULT_COLOR);
        if (color.matches("#?[0-9A-Fa-f]{3,8}")) {
            return color.startsWith("#") ? color : "#" + color;
        }
        return DEFAULT_COLOR;
    }

    private static String stringVal(Object v) {
        return v != null ? String.valueOf(v).trim() : "";
    }
}
