package org.dromara.diagnostic.report;

import org.dromara.common.core.utils.StringUtils;

import java.util.List;
import java.util.Map;

@SuppressWarnings("unchecked")
public final class WeeklyHtmlReportRenderer {

    private WeeklyHtmlReportRenderer() {
    }

    public static String render(WeeklyReportContext ctx) {
        Map<String, Object> summary = ctx.getSummary();
        Map<String, Object> geo = map(summary, "geo");
        Map<String, Object> keywords = map(summary, "keywords");
        Map<String, Object> content = map(summary, "content");
        Map<String, Object> landing = map(summary, "landing");
        Map<String, Object> leads = map(summary, "leads");
        List<String> recommendations = (List<String>) summary.get("recommendations");

        StringBuilder recHtml = new StringBuilder("<ol>");
        if (recommendations != null) {
            for (String r : recommendations) {
                recHtml.append("<li>").append(escape(r)).append("</li>");
            }
        }
        recHtml.append("</ol>");

        return """
            <!DOCTYPE html>
            <html lang="zh-CN">
            <head>
              <meta charset="UTF-8"/>
              <title>增长周报 — %s</title>
              <style>
                body { font-family: Arial, sans-serif; margin: 32px; color: #1f2937; }
                h1 { font-size: 22px; margin-bottom: 8px; }
                .meta { font-size: 13px; color: #4b5563; margin-bottom: 16px; }
                .kpi { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin: 16px 0; }
                .kpi div { background: #f9fafb; border: 1px solid #e5e7eb; padding: 12px; border-radius: 6px; }
                .kpi strong { display: block; font-size: 20px; color: #1677a0; }
                .disclaimer { background: #eff6ff; border-left: 4px solid #2563eb; padding: 12px; margin: 16px 0; font-size: 12px; }
              </style>
            </head>
            <body>
              <h1>增长周报 · %s</h1>
              <p class="meta"><strong>%s</strong> · Brand: %s · %s ~ %s</p>
              <div class="kpi">
                <div>GEO 诊断次数<strong>%s</strong>最新分 %s · Δ %s</div>
                <div>新关键词<strong>%s</strong></div>
                <div>内容任务<strong>%s</strong>已生成 %s</div>
                <div>落地页草稿<strong>%s</strong>新询盘 %s</div>
              </div>
              <h2>行动建议</h2>
              %s
              <div class="disclaimer">
                免责声明：数据来自系统统计区间，不构成 AI 推荐排名承诺。
              </div>
              <p class="meta" style="margin-top:24px">Generated by TourGEO Agent · period=%s</p>
            </body>
            </html>
            """.formatted(
            escape(ctx.getPeriod()),
            escape(ctx.getPeriod()),
            escape(ctx.getProjectName()),
            escape(ctx.getBrandName()),
            escape(ctx.getPeriodStart()),
            escape(ctx.getPeriodEnd()),
            num(geo, "runs"),
            numOrDash(geo, "latestScore"),
            delta(geo),
            num(keywords, "newCount"),
            num(content, "tasksCreated"),
            num(content, "generated"),
            num(landing, "draftCount"),
            num(leads, "newCount"),
            recHtml.toString(),
            escape(ctx.getPeriod())
        );
    }

    private static Map<String, Object> map(Map<String, Object> summary, String key) {
        Object v = summary != null ? summary.get(key) : null;
        if (v instanceof Map<?, ?> m) {
            return (Map<String, Object>) m;
        }
        return Map.of();
    }

    private static String num(Map<String, Object> m, String key) {
        if (m == null || m.get(key) == null) {
            return "0";
        }
        return String.valueOf(m.get(key));
    }

    private static String numOrDash(Map<String, Object> m, String key) {
        if (m == null || m.get(key) == null) {
            return "—";
        }
        return String.valueOf(m.get(key));
    }

    private static String delta(Map<String, Object> geo) {
        if (geo == null || geo.get("delta") == null) {
            return "—";
        }
        int d = ((Number) geo.get("delta")).intValue();
        return d >= 0 ? "+" + d : String.valueOf(d);
    }

    private static String escape(String s) {
        if (s == null) {
            return "";
        }
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    }
}
